### ISSUE TITLE
Coroutines 관련 참고자료 추가 제안

### ISSUE THREAD

**Issue by luncliff** [CppKorea/Cpp20Study#2]
> WIP

* https://isocpp.org/files/papers/N4402.pdf  
   N4402 는 최신은 아니지만 문서가 짧고 코루틴의 기본 설계이념에 대해 참고할만 한 자료입니다.
   C++ Coroutines가 어떤 표현식(Use-case)를 지원하기 위한 기능인지, 개발자의 코드가 어떻게 해석되어야 하는지에 대해 설명합니다.  
   모던 C++의 Future-Promise 의미구조(Semantics)와 코루틴의 Promise에 담기는 의미구조의 차이에 대해 이해하는데 도움이 될 것입니다.

* https://gist.github.com/MattPD/9b55db49537a90545a90447392ad3aeb   
  컨퍼런스 동영상과 라이브러리 관련 정보는 이 Gist를 참고하시는게 좋습니다.

**Comment by utilForever** [comment]
자료 추가했습니다. 감사합니다.
